services:
  db:
    image: postgres:15-alpine
    container_name: db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h localhost -p 5432 -t 5 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    build: .
    container_name: backend
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - POSTGRES_HOST=db                    # имя сервиса БД в Docker Compose
      - POSTGRES_PORT=5432
      - POSTGRES_DB=${POSTGRES_DB}                # из .env
      - POSTGRES_USER=${POSTGRES_USER}            # из .env
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "8080:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - .:/app

  celery:
    build: .
    container_name: celery
    command: celery -A config worker -l INFO -P solo --uid 8
    environment:
      - POSTGRES_HOST=db                    # имя сервиса БД в Docker Compose
      - POSTGRES_PORT=5432
      - POSTGRES_DB=${POSTGRES_DB}                # из .env
      - POSTGRES_USER=${POSTGRES_USER}            # из .env
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - .:/app

  celery_beat:
    build: .
    container_name: celery_beat
    command: celery -A config beat -l INFO
    environment:
        - POSTGRES_HOST=db                    # имя сервиса БД в Docker Compose
        - POSTGRES_PORT=5432
        - POSTGRES_DB=${POSTGRES_DB}                # из .env
        - POSTGRES_USER=${POSTGRES_USER}            # из .env
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - CELERY_BROKER_URL=redis://redis:6379/0
        - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - .:/app

volumes:
  postgres_data:
  redis_data: